<?
$PERM["search"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["contacts"]["5"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["products"]["5"]="W";
$PERM["/"]["8"]="R";
$PERM["/"]["*"]="R";
?>
