<?
$PERM["upload"]["8"]="W";
$PERM["services"]["8"]="W";
$PERM["services"]["5"]="W";
$PERM["search"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["obyavleniya"]["8"]="W";
$PERM["o-servise"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["5"]="W";
$PERM["login"]["8"]="W";
$PERM["include"]["8"]="W";
$PERM["images"]["8"]="W";
$PERM["contacts"]["8"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["8"]="W";
$PERM["company"]["5"]="W";
$PERM["bitrix"]["8"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="X";
$PERM["products"]["5"]="W";
$PERM["/"]["*"]="R";
?>